import React from "react"
import "../styles/bootstrap.min.css"
import "../styles/vendor/font-awesom/css/font-awesome.min.css"
import "../styles/vendor/mmenu/jquery.mmenu.all.css"
import "../styles/vendor/animate-wow/animate.css"
import "../styles/vendor/labelauty/labelauty.css"
import "../styles/vendor/nouislider/nouislider.min.css"
import "../styles/vendor/easydropdown/easydropdown.css"
import "../styles/vendor/skill-bars/skill-bars.css"
import "../styles/ui-spinner.css"
import "../styles/menu.css"
// import "../styles/custom.css"
import "../styles/template/basic.css"
import "../styles/template/typography.css"
import "../styles/template/pages/header-page.css"
import "../styles/template/section.css"
import "../styles/template/button.css"
import "../styles/template/breadcrumb.css"
// import "../styles/template/pagination.css"
import "../styles/template/modal.css"
import "../styles/template/object.css"
// import "../styles/template/maps.css"
// import "../styles/template/pages/agency.css"
// import "../styles/template/pages/coming-soon.css"
// import "../styles/template/pages/blog.css"
// import "../styles/template/pages/contact.css"
// import "../styles/template/pages/create-agency.css"
// import "../styles/template/pages/gallery.css"
// import "../styles/template/pages/invoice.css"
// import "../styles/template/pages/my-property.css"
// import "../styles/template/pages/new-property.css"
// import "../styles/template/pages/pricing.css"
// import "../styles/template/pages/shortcode.css"
// import "../styles/template/pages/sidebar.css"
// import "../styles/template/pages/term-condition.css"
// import "../styles/template/pages/sign-in.css"
// import "../styles/template/pages/timeline.css"
// import "../styles/template/pages/user-profile.css"
// import "../styles/template/pages/error.css"
// import "../styles/template/pages/property-page.css"
// import "../styles/template/pages/listing-page.css"
import "../styles/media-query.css"

import Nav from "./nav"

export default () => (<Nav/>)


